### ISSUE TITLE
Launch profiles dev/prod

### ISSUE THREAD

**Issue by arturboronat** [mdenet/educationplatform#143]
I usually debug an activity configuration locally in a docker image before uploading it to a public git repository for production use. This practice involves adjusting the configuration of tool URLs within the activity multiple times, depending on whether the activity is intended for development or production use.

It would greatly enhance the development workflow if a launch flag, such as --dev, could be incorporated when initiating the platform. This flag would enable the system to retrieve tool URLs from the tools-dev section rather than the standard tools section in the configuration, offering a more streamlined approach to managing these URLs.

Here is a representation of the YAML configuration illustrating the scenario:

```yaml
    tools-dev:
      - http://127.0.0.1:8073/emf-tool.yml
      - http://127.0.0.1:8500/yamtl-m2m.yml
    tools:
      - https://yamtl.github.io/playground-interfaces/static.emf/emf-tool.yml
      - https://yamtl.github.io/playground-interfaces/static.yamtlgroovy/yamtl-m2m.yml
```
