### ISSUE TITLE
Access to file raw contents (via a GET request) in activities

### ISSUE THREAD

**Issue by arturboronat** [mdenet/educationplatform#147]
### Problem

A model transformation is in production on a system deployed somewhere. The input/output models are stored on a github repository.

When this transformation needs to be demoed on the MDENet platform, the files need to be copied to a directory on the same repository where the activity configuration is found. Unfortunately, this setup forces the user to duplicate software artifacts, doubling the maintenance effort when the tranformation needs to be changed.

### Solution

Allow activities to fetch raw file contents via a url via a GET request wherever `file:` is used.

The advantage of this approach is that the software artifacts (trafos and models) can be maintained in their native environment (say as part of a CI pipeline) and they can also be used for demo purposes via the MDENet Education Platform.

**Comment by jgsuess** [comment]
For EMF the built-in resource framework allows the use of URLs to load models. This seems like duplicating functionality. Epsilon also provides a driver for CDO, which is a model storage layer. CDO can also handle transactions in MDE workflows. I would avoid reinventing.

**Comment by agarciadom** [comment]
I assume that with `file:`, you mean when the activity JSON/YAML has a `file:` key? It may be best to instead use an `url` key, to clearly distinguish the intent of the activity author.

I'm not sure if we want to overcomplicate the platform by having it interpret various kinds of URLs. It may be best to leave it to the tool function (e.g. allowing tool functions to take in parameters of type `url` and interpreting them accordingly). Epsilon (through EMF) can load arbitrary URLs.

**Comment by szschaler** [comment]
I agree we don't want to reinvent wheels here. However, some minimal support would be required from the platform. Specifically, it must be possible to provide a URL as the value of a parameter and not just a current panel.

I think all that's needed on our side is to allow action functions to be called either with the file contents (which would come from a panel currently visible to the user) or a URL provided directly in the activity specification. Not every action function will know how to handle this, but this can be managed as part of the declaration of these functions in the tool specification. How the tool decides to handle such a URL would then be up to it. We wouldn't even attempt any conversions as we would do for panel contents and we would certainly not attempt to interpret the URL in any way. 

At some point, we _may_ offer a light-touch rewrite functionality (probably based on standard JSON/YAML variable interpolation) so that we can use URLs that are only generated as part of an activity -- for example, when a student edits an Xtext grammar and generates the IDE from it, we may then want to be able to refer to the generated metamodel so we can show it graphically to the student. The URL of the meta-model file depends on URL we generate for the Xtext editor (which will be different for each student and for each session), so needs to be partly interpolated from information available only in the current browser session.

**Comment by szschaler** [comment]
BTW, note that this isn't currently on the high-prio list yet :-) Given the growing number of issues, we should perhaps start being a bit more explicit and defining release milestones or similar to be able to be clearer about the prioritisation we're doing...

**Comment by arturboronat** [comment]
Actually, there is not much to do in this feature proposal. After looking at the code in detail, it seemed that the platform already has this functionality - I tried it and it works. By the looks of it, it seems that I was not the only one unaware of this 😉 

To close this issue, the [documentation of Panel](https://github.com/mdenet/educationplatform/wiki/Creating-an-Activity#panel) needs to be updated to explain the possible values of the key `file:` in the yaml configuration of an activity. At the moment, it only mentions a relative path but it can also be a url. I wish I'd known this earlier!

An example of a configuration panel with urls below:

```yaml
panels:
- id: panel-yamtl
  name: Transformation(YAMTL)
  ref: yamtl
  file: https://raw.githubusercontent.com/yamtl/examples/master/yamtl-linkedlistreversal/src/main/groovy/linkedListReversal/ReverseLinkedList.groovy
- id: smm-panel-composite
  name: Source Metamodel
  ref: composite-panel
  childrenPanels:
    - id: panel-smm
      name: EMFatic
      ref: emfatic
      file: https://raw.githubusercontent.com/yamtl/examples/master/yamtl-linkedlistreversal/model/LinkedList.emf
    - id: panel-smm-diagram
      name: Diagram
      ref: plantuml
```
